id: ID9977CDC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T17:31:55+00:00'
last_modified: '2022-06-08T05:17:53.705127+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN2886
  title: དུས་འཁོར་རྒྱུད་མཆན་བྲིས་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '6990':
      image_group_id: I3CN2888
      title: ''
      total_pages: 1188
      order: 1
      base_file: 6990.txt
    4ABE:
      image_group_id: I3CN2889
      title: ''
      total_pages: 1100
      order: 2
      base_file: 4ABE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
