id: ID9977CDC
legacy_id: P005613
ocr_import_info:
  bdrc_scan_id: W3CN2886
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T17:23:12'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T13:11:03.631571+00:00'
last_modified: 2022-09-03 21:13:24.775971
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN2886
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW3CN2886
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དུས་འཁོར་རྒྱུད་མཆན་བྲིས་མ།
  author: ཇོ་ནང་མཁན་ཆེན་ཕྱོགས་ལས་རྣམ་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.5817903513368143
  ocr_word_median_confidence_index: 0.5799999833106995
quality: null
bases:
  I3CN2889:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN2889
      total_pages: 1100
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3CN2889.txt
    statistics:
      ocr_word_median_confidence_index: 0.5899999737739563
      ocr_word_mean_confidence_index: 0.5897722600032277
    legacy_id: v002
  I3CN2888:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN2888
      total_pages: 1188
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN2888.txt
    statistics:
      ocr_word_median_confidence_index: 0.5799999833106995
      ocr_word_mean_confidence_index: 0.5759688348389331
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
