id: P005613
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN2886
  title: དུས་འཁོར་རྒྱུད་མཆན་བྲིས་མ།
  author: ''
  volumes:
    dad79961053c4fc4a41983de7f728569:
      image_group_id: I3CN2888
      title: ''
      volume_number: 1
      total_pages: 1188
    a4b68efb3ca24fa895fa57f39e214c02:
      image_group_id: I3CN2889
      title: ''
      volume_number: 2
      total_pages: 1100
